/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Clients: () => import('#controllers/clients_controller'),
  Gateways: () => import('#controllers/gateways_controller'),
  Login: () => import('#controllers/login_controller'),
  Products: () => import('#controllers/products_controller'),
  Signup: () => import('#controllers/signup_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
}
